services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: retrouveci-postgres
    environment:
      POSTGRES_USER: retrouveci
      POSTGRES_PASSWORD: retrouveci
      POSTGRES_DB: retrouveci
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    container_name: retrouveci-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
